version: '3.2'

services:

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:0.10.2.1
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      JMX_PORT: 9992
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://:9092"
      KAFKA_PORT: 9092
      KAFKA_HOST_NAME: kafka
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 2
      KAFKA_LISTENERS: "PLAINTEXT://:9092"
      KAFKA_LOD_DIR: "/tmp/kafka-logs-0"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  kafka_1:
    image: wurstmeister/kafka:0.10.2.1
    container_name: kafka_1
    hostname: kafka_1
    ports:
      - "9093:9093"
    environment:
      JMX_PORT: 9993
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://:9093"
      KAFKA_PORT: 9093
      KAFKA_HOST_NAME: kafka_1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 2
      KAFKA_LISTENERS: "PLAINTEXT://:9093"
      KAFKA_LOG_DIR: "/tmp/kafka-logs-1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  kafka-manager:
    image: mmaia/kafka-manager:1.3.3.13
    container_name: kafka-manager
    environment:
      ZK_HOSTS: zookeeper:2181
    ports:
      - "9000:9000"
    depends_on:
      - zookeeper

  portainer:
    image: portainer/portainer:latest
    container_name: portainer
    ports:
      - "9010:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
