version: '2.1'

services:
  kafka:
    image: mmaia/kafka:0.10.2.1
    container_name: kafka
    hostname: kafka
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      JMX_PORT: 9999

  kafka-manager:
    image: mmaia/kafka-manager-docker:1.3.3.7
    container_name: kafka-manager
    environment:
      ZK_HOSTS: kafka:2181
    ports:
      - "9000:9000"
    depends_on:
      - kafka

  portainer:
    image: portainer/portainer:latest
    container_name: portainer
    ports:
      - "9010:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
