generator:
  enabled: true
  start.delay.milliseconds: 1000
  interval.milliseconds: 100
  exchange.csv:
    files: AMEX,NASDAQ,NYSE
    path: "/static/"

kafka:
  host: "kafka:9092"
  stock-quote:
    topic: stock-quote
  simple-stream:
    id: "simple-stream"
    topic: simple-stream
  stream-chain:
    id: "stream-chain"
    topic.amex: amex-quotes
    topic.nyse: nyse-quotes
    topic.nasdaq: nasdaq-quotes
  stream-enrich-produce:
    id: "stream-enrich-produce"
    topic: stream-enrich-produce

# enable all actuator endpoints from rest api.
management.security.enabled: false
