generator:
  enabled: true
  start-delay-milliseconds: 3000
  interval-milliseconds: 20
  exchange-csv:
    files:
      - AMEX
      - NASDAQ
      - NYSE
    path: "/static/"

logging:
  level:
    root: INFO
    org.apache.kafka: ERROR
    com.codespair: ERROR

kafka:
  hosts:
    - "kafka:9092"
    - "kafka_1:9093"
    - "kafka_2:9094"
  stock-quote:
    topic: stock-quote
  simple-stream:
    id: "simple-stream"
    topic: simple-stream
  stream-chain:
    id: "stream-chain"
    amexTopic: amex-quotes
    nyseTopic: nyse-quotes
    nasdaqTopic: nasdaq-quotes
  stream-enrich-produce:
    id: "stream-enrich-produce"
    topic: stream-enrich-produce

# standard spring settings ====================
# enable all actuator endpoints from rest api.
management.security.enabled: false
