generator:
  exchange.csv:
    files: AMEX,NASDAQ,NYSE
    path: "/static/"
  stockquotes:
    kafka:
      host: "kafka:9092"
      stream.app:
            id: "mock-stocks-simple-stream"
            topic: stockQuoteStreamTopic
    topic: stockQuoteTopic
    enabled: true
    start.delay.milliseconds: 1000
    interval.milliseconds: 100

# enable all actuator endpoints from rest api.
management.security.enabled: false
